- app/models/bike.rb
- db/migrate/20240527131839_create_bikes.rb
- db/schema.rb
- test/models/bike_test.rb
I added the model we need for the bikes.
Please review and let me know if everything looks good :)
> added the bike model to the database

- app/models/bike.rb
- app/models/rental.rb
- app/models/user.rb
- db/migrate/20240527135527_add_columns_to_users.rb
- db/migrate/20240527135631_add_columns_to_bikes.rb
- db/migrate/20240527135921_create_rentals.rb
- db/schema.rb
- test/models/rental_test.rb
- Add foreign key between bikes and users
- Add first_name and last_name in user table
- Add rental table
- Add foreign keys for bikes
> Adding foreing keys in bikes and user and rental table

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/home.html.erb
this is the design of the home page
> home-page-design

- app/controllers/bikes_controller.rb
- test/controllers/bikes_controller_test.rb
Hello team,
I created the bikes controller and actions.
@BPenard let me know what you think
> Added bikes controller and actions

- app/controllers/pages_controller.rb
- config/routes.rb
> Add dashboard route and method

- app/assets/stylesheets/components/_details.scss
- app/assets/stylesheets/components/_index.scss
- app/models/bike.rb
- app/views/bikes/show.html.erb
- db/seeds.rb
- fixing seeds
- creation of bike show
> Add bikes show view

- app/views/bikes/index.html.erb
- app/views/pages/home.html.erb
created the partials, can you check @BPenard ?
> Index bikes

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/bikes_controller.rb
- app/models/bike.rb
- app/views/bikes/_form_new.html.erb
- app/views/bikes/new.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20240528091316_create_active_storage_tables.active_storage.rb
- db/schema.rb
implémentation de cloudinary et quelques ajout sur le modèle bike
> scalingo-implem

- app/views/pages/home.html.erb
> i dropped the partial to include the code directly in the homepage

- app/controllers/pages_controller.rb
added the action bike.new to the page controller
can you review and accept ? thanks
@titou1987 @BPenard
> added the action bike.new to the page controller

- app/controllers/application_controller.rb
- app/controllers/bikes_controller.rb
- app/controllers/pages_controller.rb
authentication has been added for all route except 
- pages => home
- bikes => show
> add_user_auth

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_details.scss
- app/views/bikes/show.html.erb
- app/views/pages/home.html.erb
- config/environments/development.rb
- db/seeds.rb
- adding picts through cloudinary to seed
- updating home and show with cloudinary image
> adding cloudinary to seeds and fixing gem

- app/controllers/pages_controller.rb
- app/controllers/rentals_controller.rb
- config/routes.rb
- test/controllers/rentals_controller_test.rb
> Rental controller

- app/controllers/bikes_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/rentals_controller.rb
- app/views/bikes/show.html.erb
- app/views/pages/dashboard.html.erb
- config/routes.rb
> made rentals possible

- app/controllers/pages_controller.rb
- app/controllers/rentals_controller.rb
- app/views/pages/dashboard.html.erb
correction de la méthode dashboard du page contrôleur pour gérer : 
- Liste des rentals d'un loueur
- liste des bikes d'un loueur
Update de la page dashboard
- affichage en tableau des rentals
- V0 d'une liste des bikes
Modification de la méthode create d'un rental pour affecter le status "Pending par défaut"
> Dashboard renter

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form_new.scss
- app/views/pages/home.html.erb
les cartes de la page home sont maintenant clickables et redirigent vers la show du vélo sélectionné
> cards_clickable

- app/controllers/rentals_controller.rb
- app/views/rentals/renter_dashboard.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
> shipped the renter dashboard

- app/controllers/rentals_controller.rb
- app/views/bikes/new.html.erb
- app/views/pages/owner_dashboard.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/seeds.rb
add new bike button on owner dashboard
updates on owner dashboard
> Update renter dashboard

- app/assets/stylesheets/components/_addbikeform.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/bikes/_form_new.html.erb
> improved bike add

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
> finished navbar and footer
